# Generated by Django 6.0.6 on 2026-06-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_trainerremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
