# Generated by Django 6.0.6 on 2026-07-16 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_remove_placementdrive_deadline_and_more'),
        ('students', '0003_studentprofile_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='placement_students/')),
                ('job_role', models.CharField(max_length=200)),
                ('package', models.CharField(max_length=100)),
                ('placement_date', models.DateField()),
                ('success_story', models.TextField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='companies.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-placement_date'],
            },
        ),
    ]
