# Generated by Django 6.0.6 on 2026-06-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_job_jobapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementdrive',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='placementdrive',
            name='drive_date',
        ),
        migrations.RemoveField(
            model_name='placementdrive',
            name='location',
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='available_positions',
            field=models.CharField(blank=True, help_text='Example: Python Developer, QA Engineer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='coordinator_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='coordinator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='coordinator_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='drive_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='mode',
            field=models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online'), ('HYBRID', 'Hybrid')], default='OFFLINE', max_length=20),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='notice_image',
            field=models.ImageField(blank=True, null=True, upload_to='drive_notices/'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='registration_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='placementdrive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
